import type { Metadata } from "next";
import "./reset.scss";
import "./globals.scss";
import style from "./global_layout.module.scss";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Ajay Poshak&apos;s blog</title>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <body>
        <header className={style.header}>
          <h1>Ajay Poshak&apos;s blog</h1>
          <nav>
            <ul className={style.nav}>
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/about">About</Link>
              </li>
              <li>
                <Link href="/rss.xml">RSS</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
